In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
data = pd.read_csv("data_cnn_short.csv")
data.head()

T1     T2   A1   A2      F0       F1      Tau1
0  300.0  300.0  0.6  0.6  0.0016  0.00025  2902.965
1  300.0  300.0  0.6  0.7  0.0016  0.00025  2902.965
2  300.0  300.0  0.6  0.8  0.0016  0.00025  2902.965
3  300.0  300.0  0.6  0.9  0.0016  0.00025  2902.965
4  300.0  300.0  0.6  1.0  0.0016  0.00025  2902.965

In [3]:
FROGS = np.loadtxt("FROG.csv", delimiter = ",")
FROGS = FROGS.reshape(3969, 128, 128, 1)

In [18]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.max(arr)

9

In [23]:
np.random.seed(3)
shuffler = np.random.permutation(len(FROGS))

X_orig = FROGS[shuffler]
X_train = X_orig[:3200,:,:]
X_test = FROGS[3200:, :, :]

In [24]:
y_df = pd.DataFrame(columns=['T1','T2','A1','A2','F0','F1','Tau1'])
y_df["T1"] = data["T1"]/1500
y_df["T2"] = data["T2"]/1500
y_df["A1"] = data["A1"]
y_df["A2"] = data["A2"]
y_df["F0"] = data["F0"]/0.0016
y_df["F1"] = data["F1"]/0.00025
y_df["Tau1"] = data["Tau1"]/2902.965
y_df.head(20)

T1   T2   A1   A2   F0   F1  Tau1
0   0.2  0.2  0.6  0.6  1.0  1.0   1.0
1   0.2  0.2  0.6  0.7  1.0  1.0   1.0
2   0.2  0.2  0.6  0.8  1.0  1.0   1.0
3   0.2  0.2  0.6  0.9  1.0  1.0   1.0
4   0.2  0.2  0.6  1.0  1.0  1.0   1.0
5   0.2  0.2  0.6  1.1  1.0  1.0   1.0
6   0.2  0.2  0.6  1.2  1.0  1.0   1.0
7   0.2  0.2  0.6  1.3  1.0  1.0   1.0
8   0.2  0.2  0.6  1.4  1.0  1.0   1.0
9   0.2  0.2  0.7  0.6  1.0  1.0   1.0
10  0.2  0.2  0.7  0.7  1.0  1.0   1.0
11  0.2  0.2  0.7  0.8  1.0  1.0   1.0
12  0.2  0.2  0.7  0.9  1.0  1.0   1.0
13  0.2  0.2  0.7  1.0  1.0  1.0   1.0
14  0.2  0.2  0.7  1.1  1.0  1.0   1.0
15  0.2  0.2  0.7  1.2  1.0  1.0   1.0
16  0.2  0.2  0.7  1.3  1.0  1.0   1.0
17  0.2  0.2  0.7  1.4  1.0  1.0   1.0
18  0.2  0.2  0.8  0.6  1.0  1.0   1.0
19  0.2  0.2  0.8  0.7  1.0  1.0   1.0

In [25]:
Y = y_df.to_numpy()
Y_train = Y[:3200,:]
Y_test = Y[3200:,:]

In [26]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten

model = Sequential()
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(128,128,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))
model.add(Flatten())
model.add(Dense(7))

Using TensorFlow backend.


Instructions for updating:
If using Keras pass *_constraint arguments to layers.


In [27]:
model.compile(optimizer="adam", loss="mae", metrics=["accuracy"])

In [28]:
model.fit(X_train, Y_train, validation_data=(X_test, Y_test), epochs=5)


Train on 3200 samples, validate on 769 samples
Epoch 1/5
3200/3200 [==============================] - 177s 55ms/step - loss: 1.3578 - accuracy: 0.2716 - val_loss: 0.1298 - val_accuracy: 0.0000e+00
Epoch 2/5
3200/3200 [==============================] - 177s 55ms/step - loss: 0.1149 - accuracy: 0.2300 - val_loss: 0.1348 - val_accuracy: 0.3641
Epoch 3/5
3200/3200 [==============================] - 177s 55ms/step - loss: 0.1128 - accuracy: 0.2694 - val_loss: 0.1395 - val_accuracy: 0.0000e+00
Epoch 4/5
3200/3200 [==============================] - 179s 56ms/step - loss: 0.1063 - accuracy: 0.2403 - val_loss: 0.1270 - val_accuracy: 0.0455
Epoch 5/5
3200/3200 [==============================] - 212s 66ms/step - loss: 0.1083 - accuracy: 0.2181 - val_loss: 0.1544 - val_accuracy: 0.0000e+00


In [29]:
model.predict(X_test[2].reshape(1,128,128,1))

array([[0.3641916 , 0.37785664, 0.9022953 , 0.8956564 , 0.9024795 ,
        0.9430642 , 0.9095909 ]], dtype=float32)

In [30]:
Y_test[2]

array([0.53333333, 0.46666667, 1.        , 1.3       , 1.        ,
       1.        , 1.        ])

In [21]:
original_trace = np.loadtxt('trace/trace1.frg')
model.predict(original_trace.reshape(1,128,128,1))

array([[   1905.8777,   -5289.7397, -145656.73  ,   60044.914 ,
           -713.0431,   -6777.8037,   -9327.374 ]], dtype=float32)